language: node_js
node_js:
  - "stable"

install:
  - npm install

cache:
  directories:
    - "node_modules"

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true